
    element=SeleniumFunction.FindElement(driver,"variable","xpath")
    SeleniumFunction.SendData(element,"variable")
    element=SeleniumFunction.FindElement(driver,"variable","xpath")
    SeleniumFunction.SendData(element,"variable")
    element=SeleniumFunction.FindElement(driver,"variable","xpath")
    SeleniumFunction.Click(element)
    element=SeleniumFunction.FindElement(driver,"//input[@name='username']","xpath")
    SeleniumFunction.SendData(element,"netstorm")
    element=SeleniumFunction.FindElement(driver,"//input[@name='password']","xpath")
    SeleniumFunction.SendData(element,"netstorm")
    element=SeleniumFunction.FindElement(driver,"//input[@name='submit']","xpath")
    SeleniumFunction.Click(element)